name: Build LLVM (cross compile)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LLVM version to build'
        default: '18.1.8'

permissions:
  contents: write

env:
  LLVM_VERSION: ${{ inputs.version }} 
  LLVM_PROJECTS: 'clang;lldb'
  LLVM_TARGETS: 'clang-format lldb lldb-server'
  LLVM_BINS: 'clang-format lldb lldb-server'
  LLVM_LIBS: 'liblldb'

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: linux-arm64
            runner: ubuntu-latest
            BIN_EXT: ''
            SO_EXT: 'so'
            STATIC_LIB_EXT: 'a'
    runs-on: ${{ matrix.platform.runner }}
    name: ${{ matrix.platform.os }}
    steps:
      - name: Setup for macOS
        if: runner.os == 'macOS'
        run: |
          brew install cmake ninja
      - name: Setup for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y cmake ninja-build
      - name: Setup for Windows
        if: runner.os == 'Windows'
        run: |
          choco install cmake ninja curl
      - name: Get llvm
        shell: bash
        run: |
          curl -L https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/llvm-project-$LLVM_VERSION.src.tar.xz -o llvm.tar.xz
          mkdir llvm
          tar -C llvm --strip-components=1 ${{ matrix.platform.TAR_ARGS }} -xJf llvm.tar.xz
      - name: Generate build files
        shell: bash
        run: |
          cd llvm
          cmake -B build llvm -GNinja -DCMAKE_SYSTEM_NAME=cross-compile -DLLVM_HOST_TRIPLE=aarch64-unknown-linux-gnu -DLLVM_TARGETS_TO_BUILD=ARM -DLLVM_ENABLE_PROJECTS="$LLVM_PROJECTS" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DLLDB_INCLUDE_TESTS=OFF 
      - name: Build targets
        shell: bash
        run: |
          cd llvm/build
          ninja $LLVM_TARGETS
      - name: Upload products
        shell: bash
        run: |
          cd llvm/build/bin
          for BIN in $LLVM_BINS; do
            FILENAME=llvm-$LLVM_VERSION-${{ matrix.platform.os }}-$BIN

            mv $BIN $FILENAME 
            gh release upload -R npaun/bins llvm-$LLVM_VERSION $FILENAME
          done

          cd ../lib
          for LIB in $LLVM_LIBS; do
            FILENAME=llvm-$LLVM_VERSION-${{ matrix.platform.os }}-$LIB.$LLVM_VERSION.${{ matrix.platform.SO_EXT }}
            mv $LIB.$LLVM_VERSION.${{ matrix.platform.SO_EXT }} $FILENAME
            gh release upload -R npaun/bins llvm-$LLVM_VERSION $FILENAME
          done
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      
